TempVisual <- tabPanel(title = "Temporal Visualizer", 
	value = "TempVisual",
	hr(),
	column(5,
			fileInput("Metrics1", "File with the metrics:", accept = ".csv"),
			checkboxInput("Recall", "Recall", FALSE),
			checkboxInput("Precision", "Precision", FALSE),
			checkboxInput("Specificity", "Specificity", FALSE),
			checkboxInput("Accuracy", "Accuracy", TRUE),
			checkboxInput("F1Score", "F1 Score", TRUE),
			selectInput("clorol", "Color palette:",
			c("Set1" = "Set1",
			  "Set2" = "Set2",
			  "Set3" = "Set3",
			  "Accent" = "Accent",
			  "Dark" = "Dark2",
			  "Pastel1" = "Pastel1",
			  "Pastel2" = "Pastel2"
			), selected= "Set1"),
			column(2,
			       textInput("rangueiro1a", label = "1st range from:", value = 0.95),
			       textInput("rangueiro2a", label = "2nd range from", value = 0.9),
			       textInput("rangueiro3a", label = "3rd range from", value = 0.8),
			       textInput("rangueiro4a", label = "4th range from", value = 0.4),
			       textInput("rangueiro5a", label = "5th range from", value = 0),
			),
			column(2,
			       textInput("rangueiro1b", label = "1st range to:", value = 1),
			       textInput("rangueiro2b", label = "2nd range to", value = 0.95),
			       textInput("rangueiro3b", label = "3rd range to", value = 0.9),
			       textInput("rangueiro4b", label = "4th range to", value = 0.8),
			       textInput("rangueiro5b", label = "5th range to", value = 0.4),
			),
	  ),
	column(7,
		plotOutput("MetricsPlot")
	)
)
